blank_issues_enabled: false
contact_links:
  - name: Ajuda e Suporte
    url: https://github.com/seu-usuario/chatgpt-pkm/discussions
    about: Tem alguma dúvida ou quer bater um papo sobre o projeto? Junte-se às discussões!
