name: Feature Request
description: Sugira uma nova funcionalidade para o PKM ChatGPT
title: "[FEATURE]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Tem uma ideia legal para o aplicativo? Adoraríamos ouvir!
  - type: textarea
    id: problem
    attributes:
      label: Isso está relacionado a um problema?
      description: Descreva de forma clara e concisa. Exemplo "Eu fico frustrado quando..."
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
      label: Solução Proposta
      description: Descreva claramente o que você quer que aconteça. Lembre-se do visual Dark Aurora!
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternativas Consideradas
      description: Descreva soluções ou recursos alternativos que você tentou.
    validations:
      required: false
  - type: checkboxes
    id: roadmap
    attributes:
      label: Alinhamento com Roadmap
      description: Selecione se sua sugestão já faz parte do nosso Roadmap no README.
      options:
        - label: Sim, esta feature está no Roadmap
          required: false
  - type: textarea
    id: context
    attributes:
      label: Contexto Adicional / Screenshots
      description: Adicione mais informações aqui ou cole screenshots e mockups.
    validations:
      required: false
